create database naveen_varma;
CREATE TABLE COURSES(ID INT , NAME VARCHAR(50), COURSE VARCHAR(50), FEE FLOAT, CONSTRAINT PK PRIMARY KEY(ID, COURSE));

-- DML COMMANDS
-- INSERT
INSERT INTO COURSES VALUES(1, "NAVEEN", 'DATA SCIENCE', 50000);
INSERT INTO COURSES VALUES(2, "SHAIK", 'DATA ANALYTICS', 50000);
INSERT INTO COURSES VALUES(3, "SRIKANTH", 'FULL STACK', 50000);
INSERT INTO COURSES VALUES(4, "RAKHI", 'CYBER SECURITY', 50000);
SELECT * FROM COURSES;

-- Inserting data fron another table
CREATE TABLE EMP(ID INT, NAME VARCHAR(50), AGE INT,  DEPT VARCHAR(50) DEFAULT "NA");
INSERT INTO EMP(ID, NAME, AGE) VALUES (1, 'PAVAN', 24),(2, 'VENU', 24),(3, 'SRINU', 24);
SELECT * FROM EMP;

CREATE TABLE COURSES2(ID INT , NAME VARCHAR(50), COURSE VARCHAR(50), FEE FLOAT, CONSTRAINT PK PRIMARY KEY(ID, COURSE));
INSERT INTO COURSES2 VALUES(5, "RAKHI", 'CYBER', 60000);
INSERT INTO COURSES2(SELECT * FROM COURSES);
SELECT * FROM COURSES2;

-- Creating a table from an existing table
CREATE TABLE EMP_COPY AS (SELECT * FROM EMP);
SELECT * FROM EMP_COPY;

-- UPDATE
-- By default my sql cannot allow you to  update or delete the data
SET SQL_SAFE_UPDATES =0; -- Turns off safe update mode
UPDATE EMP SET DEPT="DEVELOPER" WHERE NAME ='PAVAN';
UPDATE EMP SET DEPT="DATA MINING" WHERE NAME ='VENU';
UPDATE EMP SET DEPT="PRODUCT MANGER" WHERE NAME ='SRINU';
SELECT* FROM EMP;


-- DELETE
SELECT *FROM COURSES;
DELETE FROM COURSES
WHERE ID=2;


-- ON DELETE CASACDE ON UPDATE CASCADE
CREATE TABLE PERSONS(ID INT PRIMARY KEY, LAST_NAME VARCHAR(50),F_NAME VARCHAR(50), AGE INT);
CREATE TABLE ORDERS(O_ID INT PRIMARY KEY, O_NUM INT, ID INT, FOREIGN KEY(ID) REFERENCES PERSONS(ID));
INSERT INTO PERSONS VALUES(1,'NAVEEN', 'NALLAPU', 24),(2,'SHANKAR', 'EERATI', 25),(3,'SRIKANTH', 'GUNDE', 22);
SELECT * FROM PERSONS;
INSERT INTO ORDERS VALUES(4, 6, 2),(5,7,1),(6,8,3),(7,8,2);
SELECT * FROM ORDERS;

-- CREATING TBALE WITH RULES ON DELETE CASCADE & ON UPDATE CASCADE
CREATE TABLE PERSONS1(ID INT PRIMARY KEY, LAST_NAME VARCHAR(50),F_NAME VARCHAR(50), AGE INT);
CREATE TABLE ORDERS1(O_ID INT PRIMARY KEY, O_NUM INT, ID INT, FOREIGN KEY(ID) REFERENCES PERSONS1(ID) ON DELETE CASCADE ON UPDATE CASCADE);
INSERT INTO PERSONS1 VALUES(1,'NAVEEN', 'NALLAPU', 24),(2,'SHANKAR', 'EERATI', 25),(3,'SRIKANTH', 'GUNDE', 22);
SELECT * FROM PERSONS1;
INSERT INTO ORDERS1 VALUES(4, 6, 2),(5,7,1),(6,8,3),(7,8,2);
SELECT * FROM ORDERS1;
DELETE FROM PERSONS1 WHERE AGE=22;


UPDATE PERSONS1 SET AGE=26 WHERE LAST_NAME = 'SHANKAR';
