-- JOINS 
-- PROCESS OF EXTRACTING DATA MORE THAN ONE TABLE

-- CROSS JOIN / CARTERSIAN JOIN   -- > GIVES ALL THE POSSIBLE COMBINATIONS BETWEEN THE TABLES
SELECT * FROM MEALS 
CROSS JOIN DRINKS;


-- INNER JOIN / EQUI  -- > GIVES THE COMMON RECORDS PRESENTS IN THE TABLE
SELECT * FROM CUSTOMERS
INNER JOIN ORDERS
ON CUSTOMERS.CUSTOMERID = ORDERS.ORDERID;