-- TRANSACTION CONTROL LANGUAGE

SET SQL_SAFE_UPDATES = 0;

SELECT * FROM EMPLOYEE;

-- TURN OFF THE AUTO COMMIT
SET AUTOCOMMIT= 0; -- > IT WILL TURN ON AUTOMATICALLY WHEN WE COMMIT

DELETE FROM EMPLOYEE WHERE  NAME ="BOB";
ROLLBACK;  -- > UNDO THE CHANGES
COMMIT;  -- > SAVE CHANGES PERMANENTLY

SELECT * FROM EMPLOYEE;
-- SAVEPOINT
-- TRANSACTION
START TRANSACTION;
INSERT INTO EMPLOYEE VALUES(6, "NAVEEN", "IT",100000);
UPDATE EMPLOYEE SET DEPARTMENT ="IT" WHERE NAME ="CHARLIE";
DELETE FROM EMPLOYEE WHERE ID=6;
ROLLBACK;  -- > ENTIRE TRANSACTION CAN BE ENROLLED


START TRANSACTION;
INSERT INTO EMPLOYEE VALUES(6, "NAVEEN", "IT",100000);
SAVEPOINT S1;
UPDATE EMPLOYEE SET DEPARTMENT ="IT" WHERE NAME ="CHARLIE";
SAVEPOINT S2;
DELETE FROM EMPLOYEE WHERE ID=6;
ROLLBACK TO S1;